package Consoul.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public final class Consoul__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e547e4aL, "Consoul.structure.Consoul");

  public static final SMethod<Void> process_id7LrnlOWHY3w = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("process").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).id("7LrnlOWHY3w").build();
  /*package*/ static final SMethod<Void> process_id7192NErfEh4 = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("process").modifiers(0, AccessPrivileges.PRIVATE).concept(CONCEPT).id("7192NErfEh4").build(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""), SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<String> constructResponse_id7LrnlOWICTN = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("constructResponse").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).id("7LrnlOWICTN").build(SMethodBuilder.createJavaParameter(String.class, ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(process_id7LrnlOWHY3w, process_id7192NErfEh4, constructResponse_id7LrnlOWICTN);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static void process_id7LrnlOWHY3w(@NotNull SNode __thisNode__) {
    SNode history = SLinkOperations.getTarget(__thisNode__, LINKS.history$OJz9);
    String inputText = SPropertyOperations.getString(SLinkOperations.getTarget(__thisNode__, LINKS.input$OJ57), PROPS.text$8QD4);
    inputText = inputText.strip().toLowerCase();

    if ("clear".equals(inputText)) {
      ListSequence.fromList(SLinkOperations.getChildren(history, LINKS.entries$94fv)).clear();
    } else {
      Consoul__BehaviorDescriptor.process_id7192NErfEh4.invokeSpecial(__thisNode__, history, inputText);
    }
    SPropertyOperations.assign(SLinkOperations.getTarget(__thisNode__, LINKS.input$OJ57), PROPS.text$8QD4, null);
  }
  /*package*/ static void process_id7192NErfEh4(@NotNull SNode __thisNode__, SNode history, String inputText) {
    if ("".equals(inputText)) {
      inputText = "???";
    }
    if (ListSequence.fromList(SLinkOperations.getChildren(history, LINKS.entries$94fv)).count() > 3) {
      ListSequence.fromList(SLinkOperations.getChildren(history, LINKS.entries$94fv)).removeElementAt(0);
    }

    SNodeFactoryOperations.addNewChild(history, LINKS.entries$94fv, CONCEPTS.Entry$3s);
    SPropertyOperations.assign(ListSequence.fromList(SLinkOperations.getChildren(history, LINKS.entries$94fv)).last(), PROPS.query$8Y9$, inputText);
    SPropertyOperations.assign(ListSequence.fromList(SLinkOperations.getChildren(history, LINKS.entries$94fv)).last(), PROPS.response$93yV, Consoul__BehaviorDescriptor.constructResponse_id7LrnlOWICTN.invoke(__thisNode__, inputText));
  }
  /*package*/ static String constructResponse_id7LrnlOWICTN(@NotNull SNode __thisNode__, String inputText) {
    switch (inputText) {
      case "hello":
        return "Hi!";
      case "hi":
        return "Hello!";
      case "quit":
        return "Don't be a quitter!";
      case "exit":
        return "There is no exit!";
      case "xyzzy":
        return "Nothing happens.";
      case "???":
        return "...";
      case "foo":
        return "bar";
      default:
        return "I don't know what you're talking about!";
    }
  }

  /*package*/ Consoul__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        process_id7LrnlOWHY3w(node);
        return null;
      case 1:
        process_id7192NErfEh4(node, (SNode) parameters[0], (String) parameters[1]);
        return null;
      case 2:
        return (T) ((String) constructResponse_id7LrnlOWICTN(node, (String) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink history$OJz9 = MetaAdapterFactory.getContainmentLink(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e547e4aL, 0x259902795e55b30bL, "history");
    /*package*/ static final SContainmentLink input$OJ57 = MetaAdapterFactory.getContainmentLink(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e547e4aL, 0x259902795e55b309L, "input");
    /*package*/ static final SContainmentLink entries$94fv = MetaAdapterFactory.getContainmentLink(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b300L, 0x259902795e55b307L, "entries");
  }

  private static final class PROPS {
    /*package*/ static final SProperty text$8QD4 = MetaAdapterFactory.getProperty(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b2f7L, 0x259902795e55b2f8L, "text");
    /*package*/ static final SProperty query$8Y9$ = MetaAdapterFactory.getProperty(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b301L, 0x259902795e55b302L, "query");
    /*package*/ static final SProperty response$93yV = MetaAdapterFactory.getProperty(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b301L, 0x259902795e55b304L, "response");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Entry$3s = MetaAdapterFactory.getConcept(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b301L, "Consoul.structure.Entry");
  }
}
