package Consoul.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Consoul_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Entry_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new History_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Input_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e547e4aL), MetaIdFactory.conceptId(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b301L), MetaIdFactory.conceptId(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b300L), MetaIdFactory.conceptId(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b2f7L)).seal();
}
