package Consoul.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Consoul = 0;
  public static final int Entry = 1;
  public static final int History = 2;
  public static final int Input = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL);
    builder.put(0x259902795e547e4aL, Consoul);
    builder.put(0x259902795e55b301L, Entry);
    builder.put(0x259902795e55b300L, History);
    builder.put(0x259902795e55b2f7L, Input);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
