package Consoul.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptConsoul = createDescriptorForConsoul();
  /*package*/ final ConceptDescriptor myConceptEntry = createDescriptorForEntry();
  /*package*/ final ConceptDescriptor myConceptHistory = createDescriptorForHistory();
  /*package*/ final ConceptDescriptor myConceptInput = createDescriptorForInput();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptConsoul, myConceptEntry, myConceptHistory, myConceptInput);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Consoul:
        return myConceptConsoul;
      case LanguageConceptSwitch.Entry:
        return myConceptEntry;
      case LanguageConceptSwitch.History:
        return myConceptHistory;
      case LanguageConceptSwitch.Input:
        return myConceptInput;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForConsoul() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Consoul", "Consoul", 0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e547e4aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e052cecb-b380-4c59-a290-139559855aca(Consoul.structure)/2709199371136958026");
    b.version(3);
    b.aggregate("input", 0x259902795e55b309L).target(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b2f7L).optional(false).ordered(true).multiple(false).origin("2709199371137037065").done();
    b.aggregate("history", 0x259902795e55b30bL).target(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b300L).optional(false).ordered(true).multiple(false).origin("2709199371137037067").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntry() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Consoul", "Entry", 0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b301L);
    b.class_(false, false, false);
    b.origin("r:e052cecb-b380-4c59-a290-139559855aca(Consoul.structure)/2709199371137037057");
    b.version(3);
    b.property("query", 0x259902795e55b302L).type(PrimitiveTypeId.STRING).origin("2709199371137037058").done();
    b.property("response", 0x259902795e55b304L).type(PrimitiveTypeId.STRING).origin("2709199371137037060").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHistory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Consoul", "History", 0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b300L);
    b.class_(false, false, false);
    b.origin("r:e052cecb-b380-4c59-a290-139559855aca(Consoul.structure)/2709199371137037056");
    b.version(3);
    b.aggregate("entries", 0x259902795e55b307L).target(0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b301L).optional(true).ordered(true).multiple(true).origin("2709199371137037063").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInput() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Consoul", "Input", 0xcf33fa7607f846ccL, 0x85d87e8d90785c3bL, 0x259902795e55b2f7L);
    b.class_(false, false, false);
    b.origin("r:e052cecb-b380-4c59-a290-139559855aca(Consoul.structure)/2709199371137037047");
    b.version(3);
    b.property("text", 0x259902795e55b2f8L).type(PrimitiveTypeId.STRING).origin("2709199371137037048").done();
    return b.create();
  }
}
